# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='nzbfs.proto',
  package='nzbfs',
  serialized_pb='\n\x0bnzbfs.proto\x12\x05nzbfs\"\xd9\x03\n\x04\x46ile\x12\x1e\n\x04type\x18\x01 \x02(\x0e\x32\x10.nzbfs.File.Type\x12\x10\n\x08\x66ilename\x18\x02 \x01(\t\x12\x11\n\tfile_size\x18\x03 \x01(\x04\x12\r\n\x05mtime\x18\x04 \x01(\r\x12\x0c\n\x04seen\x18\x05 \x01(\x08\x12\x0f\n\x07subject\x18\x06 \x01(\t\x12\x0e\n\x06poster\x18\x07 \x01(\t\x12\x0e\n\x06groups\x18\x08 \x03(\t\x12#\n\x05parts\x18\t \x03(\x0b\x32\x14.nzbfs.File.YencPart\x12\x19\n\x11\x66irst_file_offset\x18\n \x01(\x04\x12\x1b\n\x13\x64\x65\x66\x61ult_file_offset\x18\x0b \x01(\x04\x12\x16\n\x0e\x66irst_add_size\x18\x0c \x01(\x04\x12\x18\n\x10\x64\x65\x66\x61ult_add_size\x18\r \x01(\x04\x12\x18\n\x10\x66irst_volume_num\x18\x0e \x01(\r\x12\x1e\n\tsub_files\x18\x0f \x03(\x0b\x32\x0b.nzbfs.File\x1aZ\n\x08YencPart\x12\x12\n\nmessage_id\x18\x01 \x01(\t\x12\x0e\n\x06number\x18\x02 \x01(\r\x12\r\n\x05\x62\x65gin\x18\x03 \x01(\x04\x12\r\n\x05\x62ytes\x18\x04 \x01(\x04\x12\x0c\n\x04seen\x18\x05 \x01(\x08\"\x19\n\x04Type\x12\x08\n\x04YENC\x10\x01\x12\x07\n\x03RAR\x10\x02')



_FILE_TYPE = descriptor.EnumDescriptor(
  name='Type',
  full_name='nzbfs.File.Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='YENC', index=0, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='RAR', index=1, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=471,
  serialized_end=496,
)


_FILE_YENCPART = descriptor.Descriptor(
  name='YencPart',
  full_name='nzbfs.File.YencPart',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='message_id', full_name='nzbfs.File.YencPart.message_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='number', full_name='nzbfs.File.YencPart.number', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='begin', full_name='nzbfs.File.YencPart.begin', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='bytes', full_name='nzbfs.File.YencPart.bytes', index=3,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='seen', full_name='nzbfs.File.YencPart.seen', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=379,
  serialized_end=469,
)

_FILE = descriptor.Descriptor(
  name='File',
  full_name='nzbfs.File',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='type', full_name='nzbfs.File.type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='filename', full_name='nzbfs.File.filename', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='file_size', full_name='nzbfs.File.file_size', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='mtime', full_name='nzbfs.File.mtime', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='seen', full_name='nzbfs.File.seen', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='subject', full_name='nzbfs.File.subject', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='poster', full_name='nzbfs.File.poster', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='groups', full_name='nzbfs.File.groups', index=7,
      number=8, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='parts', full_name='nzbfs.File.parts', index=8,
      number=9, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='first_file_offset', full_name='nzbfs.File.first_file_offset', index=9,
      number=10, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='default_file_offset', full_name='nzbfs.File.default_file_offset', index=10,
      number=11, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='first_add_size', full_name='nzbfs.File.first_add_size', index=11,
      number=12, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='default_add_size', full_name='nzbfs.File.default_add_size', index=12,
      number=13, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='first_volume_num', full_name='nzbfs.File.first_volume_num', index=13,
      number=14, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='sub_files', full_name='nzbfs.File.sub_files', index=14,
      number=15, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_FILE_YENCPART, ],
  enum_types=[
    _FILE_TYPE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=23,
  serialized_end=496,
)

_FILE_YENCPART.containing_type = _FILE;
_FILE.fields_by_name['type'].enum_type = _FILE_TYPE
_FILE.fields_by_name['parts'].message_type = _FILE_YENCPART
_FILE.fields_by_name['sub_files'].message_type = _FILE
_FILE_TYPE.containing_type = _FILE;
DESCRIPTOR.message_types_by_name['File'] = _FILE

class File(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  
  class YencPart(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _FILE_YENCPART
    
    # @@protoc_insertion_point(class_scope:nzbfs.File.YencPart)
  DESCRIPTOR = _FILE
  
  # @@protoc_insertion_point(class_scope:nzbfs.File)

# @@protoc_insertion_point(module_scope)
